import numpy as np 

#Race codes: 1(NH white), 2 (NH black), 3 (native), 4 (asian), 5(hispanic), 6(Hawaiian/pacific islander),
#7(mulit+hisp), 8(multi-NH),9(unkown)
race_dict_mdcd = {
    1: "WHT",
    2: "BLCK",
    3: "AIAN",
    4: "API",
    5: "HISP",
    6: "API",
    7: "HISP",
    8: "OTH",
    9: "UNK",
    0: "UNK"
}

#Race codes: 1(NH white), 2 (NH black), 3 (NH asian), 4 (American Indian and Alaska Native (AIAN), non-Hispanic), 
#5(hispanic), 6(Hawaiian/pacific islander),
#7(mulit+hisp), 8(multi-NH),9(unkown)
race_dict_mdcd_taf = {
    1: "WHT",
    2: "BLCK",
    3: "API",
    4: "AIAN",
    5: "API",
    6: "OTH",
    7: "HISP",
    0: "UNK"
}

#MDCR Race dictionary: 0=unknown, 1=white, 2=black, 3=other, 4=asian, 5 = hispanic, 6=north american native
race_dict_mdcr = {
    0 : "UNK",
    1 : "WHT",
    2 : "BLCK",
    3 : "OTH",
    4 : "API",
    5 : "HISP",
    6 : "AIAN"
}

#MDCD sex dict #DEX sex_id: Male = 1, Female = 2, Other = nan
sex_dict_mdcd = {
    'F' : 2,
    'M' : 1,
    'U' : -1,
}

#From TOS_CD line
mdcd_dv_acause = {
            '013': '_oral',
            '029': 'exp_well_dental',
            '035': '_oral',
}

#Payer dictionary
#1 = MDCR, 2 = PRIV, 6=oth_not_mdcr,19 = oth_not_mdcd_mdcr_oop_priv
mdcr_payer_dict = {
    "A" : [2, "EGHP"], #Employer group health plan (EGHP) insurance for an aged beneficiary - PRIV
    "B" : [2, "EGHP"], # EGHP insurance for an end-stage renal disease (ESRD) beneficiary - PRIV
    "C" : [1, "MDCR"], #Conditional payment by Medicare; future reimbursement from the Public Health Service (PHS) expected
    "D" : [19, "No fault automobile insurance"],
    "E" : [19, "WC"], #Workers compensation
    "F" : [19, "PHS"], #Public Health Service (PHS) or other Federal agency (other than VA)
    "G" : [19, "LGHP"], #Working disabled beneficiary under age 65 with a local government health plan
    "H" : [19, "BL"], #Black Lung Program
    "I" : [19, "Department of Veteran's Affairs"],
    "L" : [19, "Any liability insurance"],
    "M" : [1, "MDCR"], #Override EGHP - Medicare is primary payer
    "N" : [1, "MDCR"], #Override non-EGHP - Medicare is primary payer
    "Y" : [1, "MDCR"], 
    "Z" : [1, "MDCR"],
    "None":[1, "MDCR"],
    "nan":[1, "MDCR"],
    np.nan : [1, "MDCR"],
    None : [1, "MDCR"],
    "" : [1, "MDCR"],
    "J" : [21, "UNK"], 
    "X" : [21, "UNK"], 
    "05" : [21, "UNK"] 
} 

#MSIS Dict
msis_dict= {
    1:["INPATIENT HOSPITAL","IP","F"],
    2: ["MENTAL HOSPITAL SERVICES FOR THE AGED","IP","P"],  
    4: ["INPATIENT PSYCHIATRIC FACILITY FOR INDIVIDUALS UNDER THE AGE OF 21","IP","F"],
    5: ["INTERMEDIATE CARE FACILITY (ICF) FOR THE MENTALLY RETARDED","IP","F"],  
    7: ["NURSING FACILITY SERVICES (NFS) - ALL OTHER","NF","F"], 
    8: ["PHYSICIANS", "AM","P"], 
    9: ["DENTAL","DV","P"],  
    10: ["OTHER PRACTITIONERS","OTH","P"],  
    11: ["OUTPATIENT HOSPITAL", "AM","F"], 
    12: ["CLINIC","AM","F"],  
    13: ["HOME HEALTH","HH","F"], 
    15: ["LAB AND X-RAY", "AM","P"], 
    16: ["PRESCRIBED DRUGS","RX","F"],  
    19: ["OTHER SERVICES", "OTH","F"],
    20: ["CAPITATED PAYMENTS TO HMO, HIO, OR PACE PLANS","OTH","F"],  
    21: ["CAPITATED PAYMENTS TO PREPAID HEALTH PLANS - PHPs","OTH","F"],  
    22: ["CAPITATED PAYMENTS FOR PRIMARY CARE CASE MANAGEMENT - PCCM","OTH","F"],  
    24: ["STERILIZATIONS","AM","F"],  
    25: ["ABORTIONS", "AM","F"],
    26: ["TRANSPORTATION SERVICES","AM","F"],  
    30: ["PERSONAL CARE SERVICES","AM","F"],  
    31: ["TARGETED CASE MANAGEMENT", "AM","F"], 
    33: ["REHABILITATION SERVICES","IP","P"],  
    34: ["PT, OT, SPEECH, HEARING SERVICES","AM","P"],  
    35: ["HOSPICE BENEFITS","NF","F"],  
    36: ["NURSE MIDWIFE SERVICES","AM","P"],  
    37: ["NURSE PRACTITIONER SERVICES","NF","P"],  
    38: ["PRIVATE DUTY NURSING","NF","P"],
    39: ["RELIGIOUS NON-MEDICAL HEALTH CARE INSTITUTIONS","AM","F"],
    51: ["DURABLE MEDICAL EQUIPMENT AND SUPPLIES (INCLUDING EMERGENCY RESPONSE SYSTEMS AND HOME MODIFICATIONS)","OTH","F"],
    52: ["RESIDENTIAL CARE (DEFINITION CHANGED FOR 2003 AND LATER YEARS - ADDITIONAL INFORMATION IS AVAILABLE ON REQUEST)","HH","F"],
    53: ["PSYCHIATRIC SERVICES (EXCLUDING ADULT DAY CARE)","IP","P"],
    54: ["ADULT DAY CARE","NF","F"],
    99: ["UNKNOWN","OTH","U"],
    np.nan:[np.nan,np.nan,"U"],
    #The following codes are listed as invalid by resdac
    3: ["UNKNOWN","OTH","U"],
    6: ["UNKNOWN","OTH","U"],
    14: ["UNKNOWN","OTH","U"],
    17: ["UNKNOWN","OTH","U"],
    18: ["UNKNOWN","OTH","U"],
    23: ["UNKNOWN","OTH","U"],
    27: ["UNKNOWN","OTH","U"],
    28: ["UNKNOWN","OTH","U"],
    29: ["UNKNOWN","OTH","U"],
    32: ["UNKNOWN","OTH","U"],
    40: ["UNKNOWN","OTH","U"],
    0: ["UNKNOWN","OTH","U"]
}

#These are the place of service codes used to determine toc in MDCD ot
mdcd_ot_toc = {
            2: ['AM', 'PHARMACY'], #Pharmacy not in RX data is outpatient
            3: ['AM', 'SCHOOL'], 
            4: ['OTH', 'HOMELESS SHELTER'],
            5: ['AM', 'INDIAN HEALTH SERVICE FREE-STANDING FACILITY'],
            6: ['AM', 'INDIAN HEALTH SERVIE PROVIDER-BASED FACILITY'],
            7: ['AM', 'TRIBAL 638 FREE-STANDING FACILITY'],
            8: ['AM', 'TRIBAL 638 PROVIDER-BASED FACILITY'],
            9:['OTH', 'PRISON'],
            10: ['UNK', 'N/A, Unassiagned'],
            11: ['AM', 'OFFICE'],
            12: ['HH', 'PATIENTS HOME'],
            13: ['NF', 'Assisted Living Facility'],
            14: ['NF', 'Group Home'],
            15: ['AM', 'MOBILE UNIT'],
            16: ['OTH', 'Temporary Lodging'],
            17: ['AM', 'Walk-in Retail Health Clinic'],
            18: ['AM', 'Place of Employment-Worksite'],
            19: ['AM', 'Off Campus'],
            20: ['AM', 'URGENT CARE FACILITY'],
            21: ['IP', 'INPATIENT HOSPITAL'],
            22: ['AM', 'OUTPATIENT HOSPITAL'],
            23: ['ED', 'EMERGENCY ROOM - HOSPITAL'],
            24: ['AM', 'AMBULATORY SURGERY CENTER'],
            25: ['IP', 'BIRTHING CENTER'],
            26: ['OTH', 'MILITARY TREATMENT FACILITY'],
            27: ['UNK', 'N/A, Unassiagned'],
            28: ['UNK', 'N/A, Unassiagned'],
            29: ['UNK', 'N/A, Unassiagned'],
            30: ['UNK', 'N/A, Unassiagned'],
            31: ['NF', 'Skilled Nursing facility'],
            32: ['NF', 'NURSING FACILITY'],
            33: ['NF', 'CUSTODIAL CARE FACILITY'],
            34: ['NF', 'HOSPICE'],
            41: ['OTH', 'AMBULANCE - LAND'],
            42: ['OTH', 'AMBULANCE - AIR OR WATER'],
            49: ['AM','Independent Clinic'],
            50: ['AM', 'FEDERALLY QUALIFIED HEALTH CENTER'],
            51: ['IP', 'INPATIENT PSYCHIATRIC FACILITY'], 
            52: ['AM', 'PSYCHIATRIC FACILITY PARTIAL HOSPITALIZATION'],
            53: ['AM', 'COMMUNITY MENTAL HEALTH CENTER'],
            54: ['NF', 'INTERMEDIATE CARE FACILITY FOR THE MENTALLY RETARDED'], 
            55: ['NF', 'RESIDENTIAL SUBSTANCE ABUSE TREATMENT FACILITY'],
            56: ['IP', 'PSYCHIATRIC RESIDENTIAL TREATMENT CENTER'],
            57: ['AM', 'Non-resident Subst Abuse Facil'],
            60: ['AM', 'MASS IMMUNIZATION CENTER'],
            61: ['NF', 'COMPREHENSIVE INPATIENT REHABILITATION FACILITY'],
            62: ['AM', 'COMPREHENSIVE OUTPATIENT REHABILITATION FACILITY'],
            65: ['AM', 'END STAGE RENAL DISEASE TREATMENT FACILITY '],
            71: ['AM', 'STATE OR LOCAL PUBLIC HEALTH CLINIC'],
            72: ['AM', 'RURAL HEALTH CLINIC'],
            81: ['AM', 'INDEPENDENT LABORATORY'],
            88: ['OTH', 'NOT APPLICABLE (USED WITH TYPE OF SERVICE 20, 21 OR 22)'],
            99: ['OTH', 'OTHER (NOT LISTED ABOVE) OR UNKNOWN '],
            -1: ['OTH', 'not listed on resdacs website'] }

carrier_toc = { #from NCH_CLM_TYPE_CD
    10: ['HH','Home Health Agency (HHA) claim'],
    20: ['NF','Non swing bed Skilled Nursing Facility (SNF) claim'],
    30: ['NF','Swing bed SNF claim'],
    40: ['AM','Hospital Outpatient claim'],
    50: ['NF','Hospice claim'],
    60: ['IP','Inpatient claim'],
    71: ['OTH','Local carrier non-durable medical equipment, prosthetics, orthotics, and supplies (DMEPOS) claim'],
    72: ['OTH','Local carrier DMEPOS claim'],
    81: ['OTH','Durable medical equipment regional carrier (DMERC); non-DMEPOS claim'],
    82: ['OTH','DMERC; DMEPOS claim'],
}

#These are the place of service codes used to determine toc in carrier part C
carrier_c_toc = {
            0: ['UNK', 'UNKNOWN'], 
            1: ['AM', 'PHARMACY'], 
            2: ['UNK', 'Unassigned'],
            3: ['AM', 'School'],
            4: ['OTH','Homless shelter'],
            5: ['AM','Indian Health Service - Free-standing Facility'],
            6: ['AM','Indian Health Service - Provider-based Facility'],
            7: ['AM','Tribal 638 - Free-standing Facility'],
            8: ['AM','Tribal 638 Provider-based Facility'],
            9: ['OTH','Prison/Correctional Facility'],
            10: ['UNK', 'Unassigned'],
            11: ['AM','Office'],
            12: ['HH','Home'],
            13: ['NF','Assisted Living Facility'],
            14: ['NF','Group Home'],
            15: ['AM','Mobile Unit'],
            16: ['OTH','Temporary Lodging'],
            17: ['AM','Walk-in Retail Health Clinic'],
            18: ['AM','Place of employment/worksite'],
            19: ['AM','Off campus – outpatient hospital'],
            20: ['AM','Urgent Care Facility'],
            21: ['IP','Inpatient Hospital'],
            22: ['AM','Outpatient Hospital'],
            23: ['ED','ER'],
            24: ['AM','Ambulatory Surgical Center'],
            25: ['IP','Birthing Center'],
            26: ['OTH','Military Treatment Facility'],
            27: ['UNK''UNK', 'Unassigned'],
            28: ['UNK', 'Unassigned'],
            29: ['UNK', 'Unassigned'],
            30: ['UNK', 'Unassigned'],
            31: ['NF','SNF'],
            32: ['NF','NF'],
            33: ['NF','Custodial Care Facility'],
            34: ['NF','Hospice'],
            41: ['OTH','Ambulance - Land'],
            42: ['OTH','Ambulance – Air or Water'],
            49: ['AM','Independent Clinic'],
            50: ['AM','Fed Qualified Health Ctr.'],
            51: ['IP','Inpatient Psych Facility'],
            52: ['AM','Psychiatric Facility - Partial Hospitalization'],
            53: ['AM','Community Mental Health Ctr'],
            54 :['NF','Intermediate Care/Mentally Retarded Facility'],
            55: ['NF','Residential Substance Abuse Treatment Facility'],
            56: ['IP','Psychiatric Residential Treatment Center'],
            57: ['AM','Non-residential Substance Abuse Treatment Facility'],
            58: ['UNK', 'Unassigned'],
            60: ['AM','Mass Immunization Center'],
            61: ['NF','Comprehensive Inpatient Rehabilitation Facility'],
            62: ['AM','Comprehensive Outpatient Rehabilitation Facility'],
            65: ['AM','End-Stage Renal Disease Treatment Facility'],
            71: ['AM','Public Health Clinic'],
            72: ['AM','Rural Health Clinic'],
            81: ['AM','Independent Laboratory.'],
            99: ['OTH','Other Place of Service']
             }

#Dental TOS_CD codes for MDCD TAF OT
dv_tos = ['013','029','035']

mdcr_facility_dict={#https://resdac.org/cms-data/variables/claim-facility-type-code-ffs
    1 : "Hospital",
    2 : "Skilled nursing facility",
    3 : "Home Health Agency",
    4 : "Religious Nonmedical (Hospital)",
    6 : "Intermediate care",
    7 : "Clinic or hospital-based renal dialysis facility",
    8 : "Special facility or ASC surgery",
    np.nan : np.nan
}

#Medicare discharge status to IP
mdcr_discharge = [
    2,
    9,
    43,
    70,
    82,
    85,
    93
]

#Also used for MDCD TAF OT BILL_TYPE_CD https://resdac.org/cms-data/variables/bill-type-code, in stage 2 and 3
mdcr_hh_toc_dict_1_4={
    #https://resdac.org/cms-data/variables/claim-facility-type-code-ffs
    #https://resdac.org/cms-data/variables/claim-service-classification-type-code-ffs
    1 : ['IP','Inpatient'],
    2 : ['IP','Inpatient or Home Health (covered on Part B)'],
    3 : ['AM','Outpatient (or HHA â€” covered on Part A)'],
    4 : ['IP','Other (Part B) â€” (includes HHA medical and other health services, e.g., SNF osteoporosis injectable drugs)'],
    5 : ['IP','Intermediate care â€” level I'],
    6 : ['IP','Intermediate care â€” level II'],
    7 : ['IP','Subacute Inpatient (revenue code 019X required) (formerly Intermediate care â€” level III)'],
    8 : ['IP','Swing Bed'],
    -1: ['UNK',np.nan],  
}
mdcr_hh_toc_dict_2={
    #https://resdac.org/cms-data/variables/claim-facility-type-code-ffs
    #https://resdac.org/cms-data/variables/claim-service-classification-type-code-ffs
    1 : ['NF','Inpatient'],
    2 : ['NF','Inpatient or Home Health (covered on Part B)'],
    3 : ['AM','Outpatient (or HHA â€” covered on Part A)'],
    4 : ['NF','Other (Part B) â€” (includes HHA medical and other health services, e.g., SNF osteoporosis injectable drugs)'],
    5 : ['NF','Intermediate care â€” level I'],
    6 : ['NF','Intermediate care â€” level II'],
    7 : ['NF','Subacute Inpatient (revenue code 019X required) (formerly Intermediate care â€” level III)'],
    8 : ['NF','Swing Bed'],
    -1: ['UNK',np.nan],  
}
mdcr_hh_toc_dict_3={
    #https://resdac.org/cms-data/variables/claim-facility-type-code-ffs
    #https://resdac.org/cms-data/variables/claim-service-classification-type-code-ffs
    1 : ['HH','Inpatient'],
    2 : ['HH','Inpatient or Home Health (covered on Part B)'],
    3 : ['HH','Outpatient (or HHA â€” covered on Part A)'],
    4 : ['HH','Other (Part B) â€” (includes HHA medical and other health services, e.g., SNF osteoporosis injectable drugs)'],
    5 : ['HH','Intermediate care â€” level I'],
    6 : ['HH','Intermediate care â€” level II'],
    7 : ['HH','Subacute Inpatient (revenue code 019X required) (formerly Intermediate care â€” level III)'],
    8 : ['HH','Swing Bed'],
    -1: ['UNK',np.nan],  
}
mdcr_hh_toc_dict_6={
    #https://resdac.org/cms-data/variables/claim-facility-type-code-ffs
    #https://resdac.org/cms-data/variables/claim-service-classification-type-code-ffs
    1 : ['NF','Inpatient'],
    2 : ['NF','Inpatient or Home Health (covered on Part B)'],
    3 : ['NF','Outpatient (or HHA â€” covered on Part A)'],
    4 : ['NF','Other (Part B) â€” (includes HHA medical and other health services, e.g., SNF osteoporosis injectable drugs)'],
    5 : ['NF','Intermediate care â€” level I'],
    6 : ['NF','Intermediate care â€” level II'],
    7 : ['NF','Subacute Inpatient (revenue code 019X required) (formerly Intermediate care â€” level III)'],
    8 : ['NF','Swing Bed'],
    -1: ['UNK',np.nan],  
}
mdcr_hh_toc_dict_7={
    1 : ['AM','Rural Health Clinic (RHC)'],
    2 : ['AM','Hospital based or independent renal dialysis facility'],
    3 : ['AM','Free-standing provider based federally qualified health center (FQHC)'],
    4 : ['AM','Other Rehabilitation Facility (ORF)'],
    5 : ['AM','Comprehensive Rehabilitation Center (CORF)'],
    6 : ['AM','Community Mental Health Center (CMHC)'],
    7 : ['AM','Federally Qualified Health Center (FQHC)'],
    -1: ['UNK',np.nan],  
}
mdcr_hh_toc_dict_8={
    1 : ['NF','Hospice (non-hospital based)'],
    2 : ['IP','Hospice (hospital based)'],
    3 : ['AM','Ambulatory surgical center (ASC) in hospital outpatient department'],
    4 : ['AM','Freestanding birthing center'],
    5 : ['AM','Critical Access Hospital â€” outpatient services'],
    7 : ['AM','Freestanding Non-residential Opioid Treatment Programs (eff. 1/2021)'],
    -1: ['UNK',np.nan],
}


#BLG_PRVDR_TYPE_CD
taf_ot_type_cd_dict={
    '01' : ["AM","01 = Physician"],
    '02' : ["AM","02 = Speech Language Pathologist"],
    '03' : ["DV","03 = Oral Surgery (Dentist only)"],
    '04' : ["AM","04 = Cardiac Rehabilitation and Intensive Cardiac Rehabilitation"],
    '05' : ["AM","05 = Anesthesiology Assistant"],
    '06' : ["AM","06 = Chiropractic"],
    '07' : ["AM","07 = Optometry"],
    '08' : ["AM","08 = Certified Nurse Midwife"],
    '09' : ["AM","09 = Certified Registered Nurse Anesthetist (CRNA)"],
    '10' : ["AM","10 = Mammography Center"],
    '11' : ["AM","11 = Independent Diagnostic Testing Facility (IDTF)"],
    '12' : ["AM","12 = Podiatry"],
    '13' : ["AM","13 = Ambulatory Surgical Center"],
    '14' : ["AM","14 = Nurse Practitioner"],
    '15' : ["OTH","15 = Medical Supply Company with Orthotist"],
    '16' : ["OTH","16 = Medical Supply Company with Prosthetist"],
    '17' : ["OTH","17 = Medical Supply Company with Orthotist-Prosthetist"],
    '18' : ["OTH","18 = Other Medical Supply Company"],
    '19' : ["AM","19 = Individual Certified Orthotis"],
    '20' : ["AM","20 = Individual Certified Prosthetist"],
    '21' : ["AM","21 = Individual Certified Prosthetist-Orthotist"],
    '22' : ["OTH","22 = Medical Supply Company with Pharmacis"],
    '23' : ["OTH","23 = Ambulance Service Provider"],
    '24' : ["OTH","24 = Public Health or Welfare Agency"],
    '25' : ["AM","25 = Voluntary Health or Charitable Agency"],
    '26' : ["AM","26 = Psychologist, Clinical"],
    '27' : ["AM","27 = Portable X-Ray Supplier"],
    '28' : ["AM","28 = Audiologist"],
    '29' : ["AM","29 = Physical Therapist in Private Practice"],
    '30' : ["AM","30 = Occupational Therapist in Private Practice"],
    '31' : ["AM","31 = Clinical Laboratory"],
    '32' : ["AM","32 = Clinic or Group Practice"],
    '33' : ["AM","33 = Registered Dietitian or Nutrition Professional"],
    '34' : ["AM","34 = Mass Immunizer Roster Biller"],
    '35' : ["AM","35 = Radiation Therapy Center"],
    '36' : ["AM","36 = Slide Preparation Facility"],
    '37' : ["AM","37 = Licensed Clinical Social Worker"],
    '38' : ["AM","38 = Certified Clinical Nurse Specialist"],
    '39' : ["AM","39 = Advance Diagnostic Imaging"],
    '40' : ["AM","40 = Optician"],
    '41' : ["AM","41 = Physician Assistant"],
    '42' : ["AM","42 = Hospital-General"],
    '43' : ["NF","43 = Skilled Nursing Facility"],
    '44' : ["NF","44 = Intermediate Care Nursing Facility"],
    '45' : ["NF","45 = Other Nursing Facility"],
    '46' : ["HH","46 = Home Health Agency"],
    '47' : ["AM","47 = Pharmacy"],
    '48' : ["OTH","48 = Medical Supply Company with Respiratory Therapis"],
    '49' : ["OTH","49 = Department Store"],
    '50' : ["OTH","50 = Grocery Store"],
    '51' : ["AM","51 = Indian Health Service Facility"],
    '52' : ["OTH","52 = Oxygen supplier"],
    '53' : ["AM","53 = Pedorthic personnel"],
    '54' : ["OTH","54 = Medical supply company with pedorthic personnel"],
    '55' : ["AM","55 = Rehabilitation Agency"],
    '56' : ["AM","56 = Ocularist"],
    '57' : ["AM","57 = All Other"],
    '' : ["OTH",'OTH']
}
#BLG_PRVDR_SPCLTY_CD
taf_ot_spc_cd_dict = {
    "01": ["AM", 'General Practice'],
    "02": ["AM", 'General Surgery'],
    "03": ["AM", 'Allergy/Immunology'],
    "04": ["AM", 'Otolaryngology'],
    "05": ["AM", 'Anesthesiology'],
    "06": ["AM", 'Cardiology'],
    "07": ["AM", 'Dermatology'],
    "08": ["AM", 'Family Practice'],
    "09": ["AM", 'Interventional Pain Management'],
    "10": ["AM", 'Gastroenterology'],
    "11": ["AM", 'Internal Medicine'],
    "12": ["AM", 'Osteopathic Manipulative Therapy'],
    "13": ["AM", 'Neurology'],
    "14": ["AM", 'Neurosurgery'],
    "15": ["AM", 'Speech Language Pathologist'],
    "16": ["AM", 'Obstetrics/Gynecolog'],
    "17": ["NF", 'Hospice and Palliative Care'],
    "18": ["AM", 'Ophthalmology'],
    "19": ["DV", 'Oral Surgery (dentists only'],
    "20": ["AM", 'Orthopedic Surgery'],
    "21": ["AM", 'Cardiac Electrophysiology'],
    "22": ["AM", 'Pathology'],
    "23": ["AM", 'Sports Medicine'],
    "24": ["AM", 'Plastic and Reconstructive Surgery'],
    "25": ["AM", 'Physical Medicine and Rehabilitation'],
    "26": ["AM", 'Psychiatry'],
    "27": ["AM", 'Geriatric Psychiatry'],
    "28": ["AM", 'Colorectal Surgery (formerly proctology)'],
    "29": ["AM", 'Pulmonary Disease'],
    "30": ["AM", 'Diagnostic Radiology'],
    "31": ["AM", 'Cardiac Rehabilitation & Intensive Cardiac Rehabilitation'],
    "32": ["AM", 'Anesthesiologist Assistant'],
    "33": ["AM", 'Thoracic Surgery'],
    "34": ["AM", 'Urology'],
    "35": ["AM", 'Chiropractic'],
    "36": ["AM", 'Nuclear Medicine'],
    "37": ["AM", 'Pediatric Medicine'],
    "38": ["AM", 'Geriatric Medicine'],
    "39": ["AM", 'Nephrology'],
    "40": ["AM", 'Hand Surgery'],
    "41": ["AM", 'Optometry'],
    "42": ["AM", 'Certified Nurse Midwife'],
    "43": ["AM", 'Certified Registered Nurse Anesthetist (CRNA)'],
    "44": ["AM", 'Infectious Disease'],
    "45": ["AM", 'Mammography Center'],
    "46": ["AM", 'Endocrinology'],
    "47": ["AM", 'Independent Diagnostic Testing Facility (IDTF)'],
    "48": ["AM", 'Podiatr'],
    "49": ["AM", 'Ambulatory Surgical Center'],
    "50": ["AM", 'Nurse Practitioner'],
    "51": ["OTH", 'Medical Supply Company with Orthotist'],
    "52": ["OTH", 'Medical Supply Company with Prosthetist'],
    "53": ["OTH", 'Medical Supply Company with Orthotist-Prosthetist'],
    "54": ["OTH", 'Other Medical Supply Company'],
    "55": ["AM", 'Individual Certified Orthotist'],
    "56": ["AM", 'Individual Certified Prosthetist'],
    "57": ["AM", 'Individual Certified Orthotist-Prosthetist'],
    "58": ["AM", 'Medical Supply Company with Pharmacis'],
    "59": ["OTH", 'Ambulance Service Provider'],
    "60": ["OTH", 'Public Health or Welfare Agency'],
    "61": ["AM", 'Voluntary Health or Charitable Agency'],
    "62": ["AM", 'Psychologist, Clinical'],
    "63": ["AM", 'Portable X-Ray Supplier'],
    "64": ["AM", 'Audiologist'],
    "65": ["AM", 'Physical Therapist in Private Practice'],
    "66": ["AM", 'Rheumatology'],
    "67": ["AM", 'Occupational Therapist in Private Practice'],
    "68": ["AM", 'Psychologist, Clinical'],
    "69": ["AM", 'Clinical Laboratory'],
    "70": ["AM", 'Single or Multispecialty Clinic or Group Practice'],
    "71": ["AM", 'Registered Dietitian or Nutrition Professional'],
    "72": ["AM", 'Pain Management'],
    "73": ["AM", 'Mass Immunization Roster Biller'],
    "74": ["AM", 'Radiation Therapy Center'],
    "75": ["AM", 'Slide Preparation Facility'],
    "76": ["AM", 'Peripheral Vascular Disease'],
    "77": ["AM", 'Vascular Surger'],
    "78": ["AM", 'Cardiac Surgery'],
    "79": ["AM", 'Addiction Medicine'],
    "80": ["AM", 'Licensed Clinical Social Worker'],
    "81": ["AM", 'Critical Care (Intensivists)'],
    "82": ["AM", 'Hematology'],
    "83": ["AM", 'Hematology/Oncology'],
    "84": ["AM", 'Preventive Medicine'],
    "85": ["AM", 'Maxillofacial Surgery'],
    "86": ["AM", 'Neuropsychiatry'],
    "87": ["OTH", 'All Other Suppliers'],
    "88": ["OTH", 'Unknown Supplier/Provider Specialty '],
    "89": ["AM", 'Certified Clinical Nurse Specialist'],
    "90": ["AM", 'Medical Oncology'],
    "91": ["AM", 'Surgical Oncology'],
    "92": ["AM", 'Radiation Oncology'],
    "93": ["ED", 'Emergency Medicine'],
    "94": ["AM", 'Interventional Radiology'],
    "95": ["AM", 'Advance Diagnostic Imaging'],
    "96": ["AM", 'Optician'],
    "97": ["AM", 'Physician Assistant'],
    "98": ["AM", 'Gynecological/Oncology'],
    "99": ["AM", 'Undefined physician type (provider is an MD)'],
    "A0": ["AM", 'Hospital-General'],
    "A1": ["NF", 'Skilled Nursing Facility'],
    "A2": ["NF", 'Intermediate Care Nursing Facility'],
    "A3": ["NF", 'Other Nursing Facility'],
    "A4": ["HH", 'Home Health Agency'],
    "A5": ["AM", 'Pharmacy'],
    "A6": ["OTH", 'Medical Supply Company with Respiratory Therapis'],
    "A7": ["OTH", 'Department Store'],
    "A8": ["OTH", 'Grocery Store'],
    "A9": ["AM", 'Indian Health Service facility'],
    "B1": ["OTH", 'Oxygen supplier'],
    "B2": ["AM", 'Pedorthic personnel'],
    "B3": ["OTH", 'Medical supply company with pedorthic personnel'],
    "B4": ["AM", 'Rehabilitation Agency'],
    "B5": ["AM", 'Ocularist'],
    '' : ["OTH",'OTH']
}

#https://resdac.org/cms-data/variables/bill-type-code - uses 2 and third digit of this column
taf_ot_bill_cd_dict={
    '18' : "IP",
    '15' : "IP",
    '16' : "IP",
    '11' : "IP",
    '12' : "IP",
    '17' : "IP",
    '14' : "IP",
    '13' : "AM",
    '28' : "NF",
    '25' : "NF",
    '26' : "NF",
    '21' : "NF",
    '22' : "NF",
    '27' : "NF",
    '24' : "NF",
    '23' : "AM",
    '68' : "NF",
    '65' : "NF",
    '66' : "NF",
    '61' : "NF",
    '62' : "NF",
    '67' : "NF",
    '64' : "NF",
    '63' : "NF",
    '38' : "HH",
    '35' : "HH",
    '36' : "HH",
    '31' : "HH",
    '32' : "HH",
    '37' : "HH",
    '34' : "HH",
    '33' : "HH",
    '48' : "IP",
    '45' : "IP",
    '46' : "IP",
    '41' : "IP",
    '42' : "IP",
    '47' : "IP",
    '44' : "IP",
    '43' : "AM",
    '82' : "IP",
    '81' : "NF",
    '83' : "AM",
    '89' : "AM",
    '84' : "AM",
    '85' : "AM",
    '88' : "AM",
    '86' : "IP",
    '87' : "AM",
    '71' : "AM",
    '73' : "AM",
    '76' : "AM",
    '72' : "AM",
    '75' : "AM",
    '74' : "AM",
    '79' : "AM",
    '78' : "ED",
    '-1' : "UNK"
}

#For facility type code 1 thru 6, and 9: #https://resdac.org/cms-data/variables/claim-service-classification-type-code-ffs
mdcr_serv_1_dict = {
    1 : "Inpatient",
    2 : "Inpatient or Home Health (covered on Part B)",
    3 : "Outpatient (or HHA covered on Part A)",
    4 : "Other (Part B) (Includes HHA medical and other health services, e.g., SNF osteoporosis injectable drugs)",
    5 : "Intermediate care level I",
    6 : "Intermediate care level II",
    7 : "Subacute Inpatient (revenue code 019X required) (formerly Intermediate care â€” level III)",
    8 : "Swing bed"
}
#For facility type code 7 (clinics):
mdcr_serv_7_dict = {
    1 : "Rural Health Clinic (RHC)",
    2 : "Hospital based or independent renal dialysis facility",
    3 : "Free-standing provider based federally qualified health center (FQHC)",
    4 : "Other Rehabilitation Facility (ORF)",
    5 : "Comprehensive Rehabilitation Center (CORF)",
    6 : "Community Mental Health Center (CMHC)",
    7 : "Federally Qualified Health Center (FQHC)"
}
#For facility type code 8 (special facility):
mdcr_serv_8_dict = {
    1 : "Hospice (non-hospital based)",
    2 : "Hospice (hospital based)",
    3 : "Ambulatory surgical center (ASC) in hospital outpatient department",
    4 : "Freestanding birthing center",
    5 : "Critical Access Hospital Outpatient Services"
}
#MDCR OP transaction type
mdcr_trans_dict={
    "A" : 'Outpatient Psychiatric Hospital',
    'B' : 'Outpatient tuberculosis (TB) Hospital',
    'C' : 'Outpatient General Care Hospital',
    'D' : 'Outpatient Skilled Nursing Facility (SNF)',
    'E' : 'Home Health Agency',
    'F' : 'Comprehensive Health Care',
    'G' : 'Clinical Rehab Agency',
    'H' : 'Rural Health Clinic',
    'I' : 'Satellite Dialysis Facility',
    'J' : 'Limited Care Facility',
    '0' : 'Christian Science SNF',
    '1' : 'Psychiatric Hospital Facility',
    '2' : 'TB Hospital Facility',
    '3' : 'General Care Hospital',
    '4' : 'Regular SNF',
    ' ' : 'Home Health/Hospice'
}

location_id_dict= { #first value is state location_id, second is state #
    'AL' : [523,'01'],
    'AK' : [524,'02'],
    'AZ' : [525,'04'],
    'AR' : [526,'05'],
    'CA' : [527,'06'],
    'CO' : [528,'08'],
    'CT' : [529,'09'],
    'DE' : [530,'10'],
    'DC' : [531,'11'],
    'FL' : [532,'12'],
    'GA' : [533,'13'],
    'HI' : [534,'15'],
    'ID' : [535,'16'],
    'IL' : [536,'17'],
    'IN' : [537,'18'],
    'IA' : [538,'19'],
    'KS' : [539,'20'],
    'KY' : [540,'21'],
    'LA' : [541,'22'],
    'ME' : [542,'23'],
    'MD' : [543,'24'],
    'MA' : [544,'25'],
    'MI' : [545,'26'],
    'MN' : [546,'27'],
    'MS' : [547,'28'],
    'MO' : [548,'29'],
    'MT' : [549,'30'],
    'NE' : [550,'31'],
    'NV' : [551,'32'],
    'NH' : [552,'33'],
    'NJ' : [553,'34'],
    'NM' : [554,'35'],
    'NY' : [555,'36'],
    'NC' : [556,'37'],
    'ND' : [557,'38'],
    'OH' : [558,'39'],
    'OK' : [559,'40'],
    'OR' : [560,'41'],
    'PA' : [561,'42'],
    'RI' : [562,'44'],
    'SC' : [563,'45'],
    'SD' : [564,'46'],
    'TN' : [565,'47'],
    'TX' : [566,'48'],
    'UT' : [567,'49'],
    'VT' : [568,'50'],
    'VA' : [569,'51'],
    'WA' : [570,'53'],
    'WV' : [571,'54'],
    'WI' : [572,'55'],
    'WY' : [573,'56'],
    np.nan:[np.nan,np.nan]
}

#State code dictionary both BENE_STATE_CD and PRVDR_STATE_CD use GEO_SSA_STATE_TB 
#locations that are not in US for in our state csv
ssa_state_dict = {
    # cms(SSA) state # : [state abr., state_location_id, state #] #999 indicates not a US state
    3 :[ 'AZ',525,4],
    7 : ['CT',529,9],
    40 : ['PR',999,999],
    43 : ['SD',564,46],
    48 : ['Virgin Islands',999,999],
    54 : ['Africa',999,999],
    55 : ['CA',527,6],
    56 : ['Canada & Islands',999,999],
    57 : ['Central America and West Indies',999,999],
    58 : ['Europe',999,999],
    59 : ['Mexico',999,999],
    60 : ['Oceania',999,999],
    61 : ['Philippines',999,999],
    62 : ['South America',999,999],
    63 : ['U.S. Possessions',999,999],
    64 : ['American Samoa',999,999],
    65 : ['Guam',999,999],
    66 : ['Commonwealth of the Northern Marianas Islands',999,999],
    67 :['TX',566,999],
    68 : ['FL',532,999],
    69 : ['FL',532,12],
    70 : ['KS',539,20],
    71 : ['LA',541,22],
    72 : ['OH',558,39],
    73 : ['PA',561,42],
    74 : ['TX',566,48],
    76 : [np.nan,-1,np.nan],
    80 : ['MD',543,24],
    97 : ['Northern Marianas',999,999],
    98 : ['Guam',999,999],
    99 : ['American Samoa',999,999],
    -1:[np.nan,-1,np.nan]
}

mdcd_elg=['11',
          '12',
          '14',
          '15',
          '16',
          '17',
          '21',
          '22',
          '24',
          '25',
          '31',
          '32',
          '34',
          '35',
          '3A', 
          '3',
          '41',
          '42',
          '44',
          '45',
          '48',
          '51',
          '52',
          '54',
          '55']

#State and toc also in data_schema
states=['AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'DC',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY']

toc= ["INPATIENT HOSPITAL",
      "MENTAL HOSPITAL SERVICES FOR THE AGED", 
      "INPATIENT PSYCHIATRIC FACILITY FOR INDIVIDUALS UNDER THE AGE OF 21",
      "INTERMEDIATE CARE FACILITY (ICF) FOR THE MENTALLY RETARDED", 
      "NURSING FACILITY SERVICES (NFS) - ALL OTHER",
      "PHYSICIANS",
      "DENTAL", 
      "OTHER PRACTITIONERS",
      "OUTPATIENT HOSPITAL", 
      "CLINIC","HOME HEALTH",
      "LAB AND X-RAY",
      "PRESCRIBED DRUGS",
      "OTHER SERVICES", 
      "CAPITATED PAYMENTS TO HMO, HIO, OR PACE PLANS",
      "CAPITATED PAYMENTS TO PREPAID HEALTH PLANS - PHPs", 
      "CAPITATED PAYMENTS FOR PRIMARY CARE CASE MANAGEMENT - PCCM", 
      "STERILIZATIONS",
      "ABORTIONS",
      "TRANSPORTATION SERVICES", 
      "PERSONAL CARE SERVICES",
      "TARGETED CASE MANAGEMENT",
      "REHABILITATION SERVICES", 
      "PT, OT, SPEECH, HEARING SERVICES",
      "HOSPICE BENEFITS",
      "NURSE MIDWIFE SERVICES",
      "NURSE PRACTITIONER SERVICES", 
      "PRIVATE DUTY NURSING",
      "RELIGIOUS NON-MEDICAL HEALTH CARE INSTITUTIONS", 
      "UNKNOWN"]
#-----------------------------------------
# - list of medicare-medicaid dual values
#-----------------------------------------
#https://resdac.org/cms-data/variables/monthly-medicare-medicaid-dual-eligibility-code-january
#https://resdac.org/cms-data/variables/medicare-medicaid-dual-eligibility-code-january
#TAF: https://resdac.org/sites/datadocumentation.resdac.org/files/CCW%20Codebook%20TAF%20Demographic%20Eligibility_Version%20022023.pdf
#MDCR & MDCD TAF
full_dual= [2,4,10]
part_dual=[1,3,5,6]
all_dual = full_dual + part_dual
# MDCD MAX: https://resdac.org/sites/datadocumentation.resdac.org/files/CCW%20Codebook%20MAX%20Person%20Summary_Version%202014.pdf
max_full_dual = [2,4,10,52,54,60]
max_part_dual = [1,3,5,6,7,8,9,51,53,55,56,57,58,59]
max_all_dual = max_full_dual + max_part_dual

#https://resdac.org/cms-data/variables/hmo-indicator-january "2","B","C"
#https://resdac.org/articles/identifying-medicare-managed-care-beneficiaries-master-beneficiary-summary-or-denominator
mdcr_hmo_ind=["1","2","A","B","C"]

type_clm_cd_list = [1,
                    2,
                    3,
                    4,
                    5,
                    9]

#MDCD TAF Managed care code in  CLM_TYPE_CD 
#https://resdac.org/sites/datadocumentation.resdac.org/files/2021-08/TAF_TechGuide_Claims_Files.pdf
mc_list=['2','3','4']
mc_st_specific_list=['5','B', 'C', 'E', 'V','W'] #IF the state is not ID, MO, SD, AR, AL, ME or CT